### ISSUE TITLE
Not rendering geometry

### ISSUE THREAD

**Issue by MadsHolten** [mathib/fog-demo-app#1]
Hi Mathias,

I am really interested in seeing how FOG works, but unfortunately, https://mathib.github.io/fog-demo-app/ is not working in either IE or Chrome. Any idea why?

**Comment by mathib** [comment]
@MadsHolten : wow, I totally missed this issue! It probably didn't worked at the time you were testing it, because I hosted the RDF on a graphdb cloud triplestore. The people from ontotext closed down the service over the summer so I had to look for other methods. I've found out that the Comunica query engine was well-suited for the job as it allows to query RDF files, TPF servers and SPARQL endpoints.

I've also renamed the source RDF files and just updated it in the code here. Somehow, the github pages are slow in updating, but it works if I run a clone locally.

I'm working locally on an updated version of the demo app, allowing people to add RDF sources for Comunica and with support for coordinate systems using the new [GOM ontology](https://w3id.org/gom#)
